services:
  yacht:
    image: selfhostedpro/yacht:latest
    ports:
      - '8001:8000/tcp'
    volumes:
      - 'yacht:/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: 'unless-stopped'
    platform: 'linux'
