services:
  projectsend:
    image: linuxserver/projectsend:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/projectsend/config:/config'
      - '/srv/lsio/projectsend/data:/data'
    restart: 'unless-stopped'
    platform: 'linux'
