services:
  ffmpeg:
    image: linuxserver/ffmpeg:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/ffmpeg/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
