services:
  cardigann:
    image: lscr.io/linuxserver/cardigann:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '5060:5060/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Cardigann:/config'
    restart: 'unless-stopped'
    platform: 'linux'
