services:
  mylar:
    image: linuxserver/mylar:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '8090:8090/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Mylar:/config'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
      - '${PORTAINER_ROOT}/Comics:/comics'
    restart: 'unless-stopped'
    platform: 'linux'
