services:
  pairdrop:
    image: linuxserver/pairdrop:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      RATE_LIMIT: '${RATE_LIMIT:-false}'
      WS_FALLBACK: '${WS_FALLBACK:-false}'
      RTC_CONFIG: '${RTC_CONFIG:-}'
      DEBUG_MODE: '${DEBUG_MODE:-false}'
    ports:
      - '3000:3000/tcp'
    volumes:
      - '/srv/lsio/pairdrop/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
