services:
  vaultwarden:
    image: vaultwarden/server:latest
    ports:
      - '80/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Vaultwarden:/data'
    restart: 'unless-stopped'
    platform: 'linux'
