services:
  openssh-server:
    image: linuxserver/openssh-server:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      PUBLIC_KEY: '${PUBLIC_KEY:-yourpublickey}'
      PUBLIC_KEY_FILE: '${PUBLIC_KEY_FILE:-/path/to/file}'
      PUBLIC_KEY_DIR: '${PUBLIC_KEY_DIR:-/path/to/directory/containing/_only_/pubkeys}'
      PUBLIC_KEY_URL: '${PUBLIC_KEY_URL:-https://github.com/username.keys}'
      SUDO_ACCESS: '${SUDO_ACCESS:-false}'
      PASSWORD_ACCESS: '${PASSWORD_ACCESS:-false}'
      USER_PASSWORD: '${USER_PASSWORD:-password}'
      USER_PASSWORD_FILE: '${USER_PASSWORD_FILE:-/path/to/file}'
      USER_NAME: '${USER_NAME:-linuxserver.io}'
      LOG_STDOUT: '${LOG_STDOUT:-}'
    ports:
      - '2222:2222/tcp'
    volumes:
      - '/srv/lsio/openssh-server/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
