services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '80/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/PiWigo:/config'
    restart: 'unless-stopped'
    platform: 'linux'
