services:
  oscam:
    image: linuxserver/oscam:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '8888:8888/tcp'
    volumes:
      - '/srv/lsio/oscam/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
