services:
  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '8081:8081/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/SickChill:/config'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
      - '${PORTAINER_ROOT}/TV:/tv'
    restart: 'unless-stopped'
    platform: 'linux'
