services:
  deluge-openvpn:
    image: sgtsquiggs/deluge-openvpn:latest
    environment:
      PUID: '${PUID:-1001}'
      PUID: '${PUID:-1001}'
      OPENVPN_PROVIDER: '${OPENVPN_PROVIDER:-MULLVAD}'
      OPENVPN_USERNAME: '${OPENVPN_USERNAME:-}'
      OPENVPN_PASSWORD: '${OPENVPN_PASSWORD:-}'
    ports:
      - '8112:8112/tcp'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
      - '${PORTAINER_ROOT}/Files/AppData/Config/DelugeOpenVPN/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
