services:
  cops:
    image: linuxserver/cops:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - '/srv/lsio/cops/config:/config'
      - '/srv/lsio/cops/books:/books'
    restart: 'unless-stopped'
    platform: 'linux'
