services:
  davos:
    image: linuxserver/davos:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/srv/lsio/davos/config:/config'
      - '/srv/lsio/davos/download:/download'
    restart: 'unless-stopped'
    platform: 'linux'
