services:
  your-spotify:
    image: linuxserver/your_spotify:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      APP_URL: '${APP_URL:-http://localhost}'
      SPOTIFY_PUBLIC: '${SPOTIFY_PUBLIC:-}'
      SPOTIFY_SECRET: '${SPOTIFY_SECRET:-}'
      SPOTIFY_API_DELAY_MS: '${SPOTIFY_API_DELAY_MS:-2000}'
      CORS: '${CORS:-http://localhost:80,https://localhost:443}'
      MONGO_ENDPOINT: '${MONGO_ENDPOINT:-mongodb://mongo:27017/your_spotify}'
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - '/srv/lsio/your_spotify/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
