services:
  hishtory-server:
    image: linuxserver/hishtory-server:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      HISHTORY_POSTGRES_DB: '${HISHTORY_POSTGRES_DB:-postgresql://${HISHTORY_DB_USER}:${HISHTORY_DB_PASS}@hishtory-db:5432/hishtory?sslmode=disable}'
      HISHTORY_SQLITE_DB: '${HISHTORY_SQLITE_DB:-/config/hishtory.db}'
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/srv/lsio/hishtory-server/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
