services:
  pydio-cells:
    image: linuxserver/pydio-cells:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      EXTERNALURL: '${EXTERNALURL:-yourdomain.url}'
      SERVER_IP: '${SERVER_IP:-0.0.0.0}'
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/srv/lsio/pydio-cells/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
