services:
  ubooquity:
    image: linuxserver/ubooquity:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      MAXMEM: '${MAXMEM:-}'
    ports:
      - '2202:2202/tcp'
      - '2203:2203/tcp'
    volumes:
      - '/srv/lsio/ubooquity/config:/config'
      - '/srv/lsio/ubooquity/books:/books'
      - '/srv/lsio/ubooquity/comics:/comics'
      - '/srv/lsio/ubooquity/files:/files'
    restart: 'unless-stopped'
    platform: 'linux'
