services:
  musicbrainz:
    image: lscr.io/linuxserver/musicbrainz:latest
    environment:
      BRAINZCODE: '${BRAINZCODE:-}'
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '5000:5000/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/MusicBrainz:/config'
      - '${PORTAINER_ROOT}/Files/AppData/MusicBrainz:/data'
    restart: 'unless-stopped'
    platform: 'linux'
