services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '5055:5055/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Jellyseerr:/app/config'
    restart: 'unless-stopped'
    platform: 'linux'
