services:
  swag:
    image: linuxserver/swag:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      URL: '${URL:-example.com}'
      VALIDATION: '${VALIDATION:-http}'
      SUBDOMAINS: '${SUBDOMAINS:-www,}'
      CERTPROVIDER: '${CERTPROVIDER:-}'
      CERT_PROFILE: '${CERT_PROFILE:-}'
      DNSPLUGIN: '${DNSPLUGIN:-cloudflare}'
      PROPAGATION: '${PROPAGATION:-}'
      EMAIL: '${EMAIL:-}'
      ONLY_SUBDOMAINS: '${ONLY_SUBDOMAINS:-false}'
      EXTRA_DOMAINS: '${EXTRA_DOMAINS:-}'
      STAGING: '${STAGING:-false}'
      DISABLE_F2B: '${DISABLE_F2B:-}'
      SWAG_AUTORELOAD: '${SWAG_AUTORELOAD:-}'
      SWAG_AUTORELOAD_WATCHLIST: '${SWAG_AUTORELOAD_WATCHLIST:-}'
    ports:
      - '443:443/tcp'
      - '80:80/tcp'
      - '443:443/udp'
    volumes:
      - '/srv/lsio/swag/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
