services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '9696:9696/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Prowlarr:/config'
    restart: 'unless-stopped'
    platform: 'linux'
