services:
  radarr:
    image: linuxserver/radarr:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '7878:7878/tcp'
    volumes:
      - '/srv/lsio/radarr/config:/config'
      - '/srv/lsio/radarr/movies:/movies'
      - '/srv/lsio/radarr/downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
