services:
  chowdown:
    image: gregyankovoy/chowdown:latest
    ports:
      - '4000:4000/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Chowdown:/config'
    restart: 'unless-stopped'
    platform: 'linux'
