services:
  nginx:
    image: linuxserver/nginx:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '80/tcp'
      - '443/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Nginx:/config'
    restart: 'unless-stopped'
    platform: 'linux'
