services:
  lychee:
    image: linuxserver/lychee:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      DB_CONNECTION: '${DB_CONNECTION:-}'
      DB_HOST: '${DB_HOST:-}'
      DB_PORT: '${DB_PORT:-}'
      DB_USERNAME: '${DB_USERNAME:-}'
      DB_PASSWORD: '${DB_PASSWORD:-}'
      DB_DATABASE: '${DB_DATABASE:-}'
      APP_NAME: '${APP_NAME:-Lychee}'
      APP_URL: '${APP_URL:-}'
      TRUSTED_PROXIES: '${TRUSTED_PROXIES:-}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/lychee/config:/config'
      - '/srv/lsio/lychee/pictures:/pictures'
    restart: 'unless-stopped'
    platform: 'linux'
