services:
  smokeping:
    image: linuxserver/smokeping:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      MASTER_URL: '${MASTER_URL:-http://<master-host-ip>:80/smokeping/}'
      SHARED_SECRET: '${SHARED_SECRET:-password}'
      CACHE_DIR: '${CACHE_DIR:-/tmp}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/smokeping/config:/config'
      - '/srv/lsio/smokeping/data:/data'
    restart: 'unless-stopped'
    platform: 'linux'
