services:
  smokeping:
    image: linuxserver/smokeping:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '80/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Smokeping:/config'
      - '${PORTAINER_ROOT}/Files/AppData/Smokeping:/data'
    restart: 'unless-stopped'
    platform: 'linux'
