services:
  guacamole:
    image: oznu/guacamole:latest
    ports:
      - '8080:8080/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Guacamole:/config'
    restart: 'unless-stopped'
    platform: 'linux'
