services:
  pwndrop:
    image: linuxserver/pwndrop:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      SECRET_PATH: '${SECRET_PATH:-/pwndrop}'
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/srv/lsio/pwndrop/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
