services:
  code-server:
    image: linuxserver/code-server:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      PASSWORD: '${PASSWORD:-password}'
      HASHED_PASSWORD: '${HASHED_PASSWORD:-}'
      SUDO_PASSWORD: '${SUDO_PASSWORD:-password}'
      SUDO_PASSWORD_HASH: '${SUDO_PASSWORD_HASH:-}'
      PROXY_DOMAIN: '${PROXY_DOMAIN:-code-server.my.domain}'
      DEFAULT_WORKSPACE: '${DEFAULT_WORKSPACE:-/config/workspace}'
      PWA_APPNAME: '${PWA_APPNAME:-code-server}'
    ports:
      - '8443:8443/tcp'
    volumes:
      - '/srv/lsio/code-server/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
