services:
  nzbhydra2:
    image: linuxserver/nzbhydra2:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '5076:5076/tcp'
    volumes:
      - '/srv/lsio/nzbhydra2/config:/config'
      - '/srv/lsio/nzbhydra2/downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
