services:
  ldap-auth:
    image: linuxserver/ldap-auth:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      FERNETKEY: '${FERNETKEY:-}'
      CERTFILE: '${CERTFILE:-}'
      KEYFILE: '${KEYFILE:-}'
    ports:
      - '8888:8888/tcp'
      - '9000:9000/tcp'
    volumes:
      - '/srv/lsio/ldap-auth/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
