services:
  duplicati:
    image: linuxserver/duplicati:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      SETTINGS_ENCRYPTION_KEY: '${SETTINGS_ENCRYPTION_KEY:-}'
      CLI_ARGS: '${CLI_ARGS:-}'
      DUPLICATI__WEBSERVICE_PASSWORD: '${DUPLICATI__WEBSERVICE_PASSWORD:-}'
    ports:
      - '8200:8200/tcp'
    volumes:
      - '/srv/lsio/duplicati/config:/config'
      - '/srv/lsio/duplicati/backups:/backups'
      - '/srv/lsio/duplicati/source:/source'
    restart: 'unless-stopped'
    platform: 'linux'
