services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
      OPENVPN_PROVIDER: '${OPENVPN_PROVIDER:-MULLVAD}'
      OPENVPN_USERNAME: '${OPENVPN_USERNAME:-}'
      OPENVPN_PASSWORD: '${OPENVPN_PASSWORD:-}'
      LOCAL_NETWORK: '${LOCAL_NETWORK:-192.168.0.0/24}'
    ports:
      - '9091:9091/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Downloads:/data'
      - '/etc/localtime:/etc/localtime'
    restart: 'unless-stopped'
    platform: 'linux'
