services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '8686:8686/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Lidarr:/config'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
      - '${PORTAINER_ROOT}/Music:/music'
    restart: 'unless-stopped'
    platform: 'linux'
