services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:latest
    ports:
      - '143/tcp'
      - '25/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/ProtonMail-Bridge:/root'
    restart: 'unless-stopped'
    platform: 'linux'
