services:
  kometa:
    image: linuxserver/kometa:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      KOMETA_CONFIG: '${KOMETA_CONFIG:-/config/config.yml}'
      KOMETA_TIMES: '${KOMETA_TIMES:-03:00}'
      KOMETA_RUN: '${KOMETA_RUN:-False}'
      KOMETA_TESTS: '${KOMETA_TESTS:-False}'
      KOMETA_NO_MISSING: '${KOMETA_NO_MISSING:-False}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/kometa/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
