services:
  thelounge:
    image: linuxserver/thelounge:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '9000:9000/tcp'
    volumes:
      - '/srv/lsio/thelounge/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
