services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '8080:8080/tcp'
      - '9090:9090/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Sabnzbd:/config'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
      - '${PORTAINER_ROOT}/Downloads/incomplete:/incomplete-downloads'
    restart: 'unless-stopped'
    platform: 'linux'
