services:
  heimdall:
    image: linuxserver/heimdall:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      ALLOW_INTERNAL_REQUESTS: '${ALLOW_INTERNAL_REQUESTS:-false}'
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - '/srv/lsio/heimdall/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
