services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      DOCKER_MODS: '${DOCKER_MODS:-linuxserver/mods:universal-calibre}'
      OAUTHLIB_RELAX_TOKEN_SCOPE: '${OAUTHLIB_RELAX_TOKEN_SCOPE:-1}'
    ports:
      - '8083:8083/tcp'
    volumes:
      - '/srv/lsio/calibre-web/config:/config'
      - '/srv/lsio/calibre-web/books:/books'
    restart: 'unless-stopped'
    platform: 'linux'
