services:
  babybuddy:
    image: linuxserver/babybuddy:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      CSRF_TRUSTED_ORIGINS: '${CSRF_TRUSTED_ORIGINS:-http://127.0.0.1:8000,https://babybuddy.domain.com}'
    ports:
      - '8000:8000/tcp'
    volumes:
      - '/srv/lsio/babybuddy/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
