services:
  raneto:
    image: linuxserver/raneto:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '3000:3000/tcp'
    volumes:
      - '/srv/lsio/raneto/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
