services:
  flexget:
    image: linuxserver/flexget:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      FG_LOG_LEVEL: '${FG_LOG_LEVEL:-info}'
      FG_LOG_FILE: '${FG_LOG_FILE:-/config/flexget.log}'
      FG_CONFIG_FILE: '${FG_CONFIG_FILE:-/config/.flexget/config.yml}'
      FG_WEBUI_PASSWORD: '${FG_WEBUI_PASSWORD:-info}'
    ports:
      - '5050:5050/tcp'
    volumes:
      - '/srv/lsio/flexget/config:/config'
      - '/srv/lsio/flexget/data:/data'
    restart: 'unless-stopped'
    platform: 'linux'
