services:
  pelorus:
    image: linuxserver/pelorus:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '3001:3001/tcp'
    volumes:
      - '/srv/lsio/pelorus/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
