services:
  chevereto:
    image: nmtan/chevereto:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
      CHEVERETO_DB_HOST: '${CHEVERETO_DB_HOST:-}'
      CHEVERETO_DB_USERNAME: '${CHEVERETO_DB_USERNAME:-}'
      CHEVERETO_DB_PASSWORD: '${CHEVERETO_DB_PASSWORD:-}'
      CHEVERETO_DB_NAME: '${CHEVERETO_DB_NAME:-}'
      CHEVERETO_DB_PREFIX: '${CHEVERETO_DB_PREFIX:-}'
    ports:
      - '80/tcp'
    volumes:
      - '/var/www/html/images'
    restart: 'unless-stopped'
    platform: 'linux'
