services:
  calibre:
    image: linuxserver/calibre:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      PASSWORD: '${PASSWORD:-}'
      CLI_ARGS: '${CLI_ARGS:-}'
    ports:
      - '8080:8080/tcp'
      - '8181:8181/tcp'
      - '8081:8081/tcp'
    volumes:
      - '/srv/lsio/calibre/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
