services:
  homer:
    image: b4bz/homer:latest
    ports:
      - '8902:8080/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Homer/assets:/www/assets'
      - '${PORTAINER_ROOT}/Files/AppData/Config/Homer:/www/config.yml'
    restart: 'unless-stopped'
    platform: 'linux'
