services:
  filebrowser:
    image: 80x86/filebrowser:latest
    ports:
      - '8082:8082/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/FileBrowser:/config'
      - '${PORTAINER_ROOT}/Files/AppData/Config:/myfiles'
    restart: 'unless-stopped'
    platform: 'linux'
