services:
  adguardhome-sync:
    image: linuxserver/adguardhome-sync:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      CONFIGFILE: '${CONFIGFILE:-/config/adguardhome-sync.yaml}'
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/srv/lsio/adguardhome-sync/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
