services:
  tvheadend:
    image: linuxserver/tvheadend:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      RUN_OPTS: '${RUN_OPTS:-}'
    ports:
      - '9981:9981/tcp'
      - '9982:9982/tcp'
    volumes:
      - '/srv/lsio/tvheadend/config:/config'
      - '/srv/lsio/tvheadend/recordings:/recordings'
    restart: 'unless-stopped'
    platform: 'linux'
