services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    ports:
      - '5000:5000/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Dashmachine:/dashmachine/dashmachine/user_data'
    restart: 'unless-stopped'
    platform: 'linux'
