services:
  beets:
    image: linuxserver/beets:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '8337:8337/tcp'
    volumes:
      - '/srv/lsio/beets/config:/config'
      - '/srv/lsio/beets/music:/music'
      - '/srv/lsio/beets/downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
