services:
  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      PMA_ARBITRARY: '${PMA_ARBITRARY:-1}'
      PMA_ABSOLUTE_URI: '${PMA_ABSOLUTE_URI:-https://phpmyadmin.example.com}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/phpmyadmin/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
