services:
  apprise-api:
    image: linuxserver/apprise-api:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      APPRISE_ATTACH_SIZE: '${APPRISE_ATTACH_SIZE:-0}'
    ports:
      - '8000:8000/tcp'
    volumes:
      - '/srv/lsio/apprise-api/config:/config'
      - '/srv/lsio/apprise-api/attachments:/attachments'
    restart: 'unless-stopped'
    platform: 'linux'
