services:
  murmur:
    image: goofball222/murmur:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
      TZ: '${TZ:-}'
    ports:
      - '64738:64738/tcp'
      - '64738:64738/udp'
    volumes:
      - '/etc/localtime:ro:/etc/localtime'
      - '${PORTAINER_ROOT}/Files/Config/Murmur:/opt/murmur/config'
      - '${PORTAINER_ROOT}/Files/Murmur/data:/opt/murmur/data'
      - '${PORTAINER_ROOT}/Files/Murmur/log:/opt/murmur/log'
    restart: 'unless-stopped'
    platform: 'linux'
