services:
  bookstack:
    image: linuxserver/bookstack:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      APP_URL: '${APP_URL:-}'
      APP_KEY: '${APP_KEY:-}'
      DB_HOST: '${DB_HOST:-}'
      DB_PORT: '${DB_PORT:-3306}'
      DB_USERNAME: '${DB_USERNAME:-}'
      DB_PASSWORD: '${DB_PASSWORD:-}'
      DB_DATABASE: '${DB_DATABASE:-}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION:-}'
    ports:
      - '6875:80/tcp'
    volumes:
      - '/srv/lsio/bookstack/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
