services:
  diskover:
    image: linuxserver/diskover:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      ES_HOST: '${ES_HOST:-elasticsearch}'
      ES_PORT: '${ES_PORT:-9200}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/diskover/config:/config'
      - '/srv/lsio/diskover/data:/data'
    restart: 'unless-stopped'
    platform: 'linux'
