services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
      TZ: '${TZ:-}'
    ports:
      - '8096:8096/tcp'
      - '8920:8920/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Jelllyfin:/config'
      - '${PORTAINER_ROOT}/TV:/data/tvshows'
      - '${PORTAINER_ROOT}/Movies:/data/movies'
    restart: 'unless-stopped'
    platform: 'linux'
