services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '8080:8080/tcp'
      - '8081:8081/tcp'
      - '8443:8443/tcp'
      - '8843:8843/tcp'
      - '8880:8880/tcp'
      - '6789:6789/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Unifi:/config'
    restart: 'unless-stopped'
    platform: 'linux'
