services:
  mcmyadmin2:
    image: lscr.io/linuxserver/mcmyadmin2:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '8080:8080/tcp'
      - '25565:25565/tcp'
    volumes:
      - '/minecraft'
    restart: 'unless-stopped'
    platform: 'linux'
