services:
  transmission:
    image: linuxserver/transmission:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      TRANSMISSION_WEB_HOME: '${TRANSMISSION_WEB_HOME:-}'
      USER: '${USER:-}'
      PASS: '${PASS:-}'
      WHITELIST: '${WHITELIST:-}'
      PEERPORT: '${PEERPORT:-}'
      HOST_WHITELIST: '${HOST_WHITELIST:-}'
    ports:
      - '9091:9091/tcp'
      - '51413:51413/tcp'
      - '51413:51413/udp'
    volumes:
      - '/srv/lsio/transmission/config:/config'
      - '/srv/lsio/transmission/downloads:/downloads'
      - '/srv/lsio/transmission/watch:/watch'
    restart: 'unless-stopped'
    platform: 'linux'
