services:
  nzbhydra2:
    image: linuxserver/nzbhydra2:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '5076:5076/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Nzbhydra2:/config'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
