services:
  manyfold:
    image: linuxserver/manyfold:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      DATABASE_URL: '${DATABASE_URL:-}'
      REDIS_URL: '${REDIS_URL:-}'
      SECRET_KEY_BASE: '${SECRET_KEY_BASE:-}'
    ports:
      - '3214:3214/tcp'
    volumes:
      - '/srv/lsio/manyfold/config:/config'
      - '/srv/lsio/manyfold/libraries:/libraries'
    restart: 'unless-stopped'
    platform: 'linux'
