services:
  chromium:
    image: linuxserver/chromium:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      CHROME_CLI: '${CHROME_CLI:-https://www.linuxserver.io/}'
    ports:
      - '3000:3000/tcp'
      - '3001:3001/tcp'
    volumes:
      - '/srv/lsio/chromium/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
