services:
  tt-rss:
    image: lunik1/tt-rss:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '80/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/tt-rss:/config'
    restart: 'unless-stopped'
    platform: 'linux'
