services:
  qemu-static:
    image: linuxserver/qemu-static:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/qemu-static/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
