services:
  changedetection-io:
    image: linuxserver/changedetection.io:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      BASE_URL: '${BASE_URL:-}'
      PLAYWRIGHT_DRIVER_URL: '${PLAYWRIGHT_DRIVER_URL:-}'
    ports:
      - '5000:5000/tcp'
    volumes:
      - '/srv/lsio/changedetection.io/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
