services:
  kodi-headless:
    image: lscr.io/linuxserver/kodi-headless:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '8080/tcp'
      - '9777/udp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Kodi:/config'
    restart: 'unless-stopped'
    platform: 'linux'
