services:
  medusa:
    image: linuxserver/medusa:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '8081:8081/tcp'
    volumes:
      - '/srv/lsio/medusa/config:/config'
      - '/srv/lsio/medusa/downloads:/downloads'
      - '/srv/lsio/medusa/tv:/tv'
    restart: 'unless-stopped'
    platform: 'linux'
