services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '8080:8080/tcp'
    volumes:
      - '/srv/lsio/sabnzbd/config:/config'
      - '/srv/lsio/sabnzbd/incomplete-downloads:/incomplete-downloads'
      - '/srv/lsio/sabnzbd/downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
