services:
  plex:
    image: linuxserver/plex:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      VERSION: '${VERSION:-docker}'
      PLEX_CLAIM: '${PLEX_CLAIM:-}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/plex/config:/config'
      - '/srv/lsio/plex/tv:/tv'
      - '/srv/lsio/plex/movies:/movies'
    restart: 'unless-stopped'
    platform: 'linux'
