services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '443:443/tcp'
    volumes:
      - '/srv/lsio/nextcloud/config:/config'
      - '/srv/lsio/nextcloud/data:/data'
    restart: 'unless-stopped'
    platform: 'linux'
