services:
  kavita:
    image: linuxserver/kavita:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '5000:5000/tcp'
    volumes:
      - '/srv/lsio/kavita/config:/config'
      - '/srv/lsio/kavita/data:/data'
    restart: 'unless-stopped'
    platform: 'linux'
