services:
  ngircd:
    image: linuxserver/ngircd:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '6667:6667/tcp'
    volumes:
      - '/srv/lsio/ngircd/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
