services:
  foldingathome:
    image: linuxserver/foldingathome:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      ACCOUNT_TOKEN: '${ACCOUNT_TOKEN:-}'
      MACHINE_NAME: '${MACHINE_NAME:-}'
      CLI_ARGS: '${CLI_ARGS:-}'
    ports:
      - '80:80/tcp'
      - '7396:7396/tcp'
    volumes:
      - '/srv/lsio/foldingathome/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
