services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - '3001:3001/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/UptimeKuma:/app/data'
    restart: 'always'
    platform: 'linux'
