services:
  lidarr:
    image: linuxserver/lidarr:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
    ports:
      - '8686:8686/tcp'
    volumes:
      - '/srv/lsio/lidarr/config:/config'
      - '/srv/lsio/lidarr/music:/music'
      - '/srv/lsio/lidarr/downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
