services:
  vscodium-web:
    image: linuxserver/vscodium-web:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      CONNECTION_TOKEN: '${CONNECTION_TOKEN:-}'
      CONNECTION_TOKEN_FILE: '${CONNECTION_TOKEN_FILE:-}'
      SUDO_PASSWORD: '${SUDO_PASSWORD:-password}'
      SUDO_PASSWORD_HASH: '${SUDO_PASSWORD_HASH:-}'
      CODE_ARGS: '${CODE_ARGS:-}'
    ports:
      - '8000:8000/tcp'
    volumes:
      - '/srv/lsio/vscodium-web/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
