services:
  librewolf:
    image: linuxserver/librewolf:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      LIBREWOLF_CLI: '${LIBREWOLF_CLI:-https://www.linuxserver.io/}'
    ports:
      - '3000:3000/tcp'
      - '3001:3001/tcp'
    volumes:
      - '/srv/lsio/librewolf/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
