services:
  habridge:
    image: linuxserver/habridge:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      SEC_KEY: '${SEC_KEY:-}'
    ports:
      - '8080:8080/tcp'
      - '50000:50000/tcp'
    volumes:
      - '/srv/lsio/habridge/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
