services:
  nzbget:
    image: linuxserver/nzbget:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      NZBGET_USER: '${NZBGET_USER:-nzbget}'
      NZBGET_PASS: '${NZBGET_PASS:-tegbzn6789}'
    ports:
      - '6789:6789/tcp'
    volumes:
      - '/srv/lsio/nzbget/config:/config'
      - '/srv/lsio/nzbget/downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
