services:
  nzbget:
    image: linuxserver/nzbget:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-100}'
    ports:
      - '6789:6789/tcp'
    volumes:
      - '${PORTAINER_ROOT}/Files/AppData/Config/Nzbget:/config'
      - '${PORTAINER_ROOT}/Downloads:/downloads'
    restart: 'unless-stopped'
    platform: 'linux'
