services:
  synclounge:
    image: linuxserver/synclounge:latest
    environment:
      AUTH_LIST: '${AUTH_LIST:-plexuser1,plexuser2,email1,machineid1}'
    ports:
      - '8088:8088/tcp'
    volumes:
      - '/srv/lsio/synclounge/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
