services:
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      APP_KEY: '${APP_KEY:-}'
      APP_URL: '${APP_URL:-}'
      DB_CONNECTION: '${DB_CONNECTION:-sqlite}'
      SPEEDTEST_SCHEDULE: '${SPEEDTEST_SCHEDULE:-}'
      SPEEDTEST_SERVERS: '${SPEEDTEST_SERVERS:-}'
      DB_HOST: '${DB_HOST:-}'
      DB_PORT: '${DB_PORT:-}'
      DB_DATABASE: '${DB_DATABASE:-}'
      DB_USERNAME: '${DB_USERNAME:-}'
      DB_PASSWORD: '${DB_PASSWORD:-}'
      DISPLAY_TIMEZONE: '${DISPLAY_TIMEZONE:-Etc/UTC}'
      PRUNE_RESULTS_OLDER_THAN: '${PRUNE_RESULTS_OLDER_THAN:-0}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/speedtest-tracker/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
