services:
  duckdns:
    image: linuxserver/duckdns:latest
    environment:
      PUID: '${PUID:-1000}'
      PGID: '${PGID:-1000}'
      TZ: '${TZ:-Etc/UTC}'
      SUBDOMAINS: '${SUBDOMAINS:-subdomain1,subdomain2}'
      TOKEN: '${TOKEN:-token}'
      UPDATE_IP: '${UPDATE_IP:-ipv4}'
      LOG_FILE: '${LOG_FILE:-false}'
    ports:
      - '80:80/tcp'
    volumes:
      - '/srv/lsio/duckdns/config:/config'
      - '/srv/lsio/duckdns/config:/config'
    restart: 'unless-stopped'
    platform: 'linux'
